// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGsQDzEUfJeAhddsGHUtzBc4t17SCUNIg',
    appId: '1:299569825147:web:a728766d2965bfeb7f69de',
    messagingSenderId: '299569825147',
    projectId: 'drape-c1e40',
    authDomain: 'drape-c1e40.firebaseapp.com',
    storageBucket: 'drape-c1e40.firebasestorage.app',
    measurementId: 'G-PB90JQ29HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVSEqLaH2tzvbIpeWBrqZfGzZEwbdTD8',
    appId: '1:299569825147:android:e3a7380be188b3d17f69de',
    messagingSenderId: '299569825147',
    projectId: 'drape-c1e40',
    storageBucket: 'drape-c1e40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVQYgEdK6iamgb41l662A01gUTpqaZ4ig',
    appId: '1:299569825147:ios:3e34788d182f777b7f69de',
    messagingSenderId: '299569825147',
    projectId: 'drape-c1e40',
    storageBucket: 'drape-c1e40.firebasestorage.app',
    iosBundleId: 'com.example.drape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVQYgEdK6iamgb41l662A01gUTpqaZ4ig',
    appId: '1:299569825147:ios:3e34788d182f777b7f69de',
    messagingSenderId: '299569825147',
    projectId: 'drape-c1e40',
    storageBucket: 'drape-c1e40.firebasestorage.app',
    iosBundleId: 'com.example.drape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGsQDzEUfJeAhddsGHUtzBc4t17SCUNIg',
    appId: '1:299569825147:web:df234c9a889bea057f69de',
    messagingSenderId: '299569825147',
    projectId: 'drape-c1e40',
    authDomain: 'drape-c1e40.firebaseapp.com',
    storageBucket: 'drape-c1e40.firebasestorage.app',
    measurementId: 'G-G48JZ7LQD8',
  );
}
